import type { TaskAttachment } from "@/components/common/FileUpload";

export interface Project {
  id: string;
  project_name: string;
  project_image: string;
  description: string;
  status: "Active" | "On Hold" | "Completed";
  priority: "Low" | "Medium" | "High";
  attachments: TaskAttachment[];
  start_date: string;
  end_date: string;
  created_by: string;
  created_at: string;
}

export const projectData: Project[] = [
  {
    id: crypto.randomUUID(),
    project_name: "Project Alpha",
    project_image: "https://picsum.photos/80?1",
    description: "Project management dashboard redesign.",
    status: "Active",
    priority: "High",
    start_date: "2026-08-01",
    end_date: "2026-10-15",
    created_by: "Alex",
    created_at: "2026-08-01",

    attachments: [],
  },
  {
    id: crypto.randomUUID(),
    project_name: "CRM System",
    project_image: "https://picsum.photos/80?2",
    description: "Customer relationship management system.",
    status: "On Hold",
    priority: "Medium",
    start_date: "2026-07-20",
    end_date: "2026-09-30",
    created_by: "Sam",
    created_at: "2026-07-20",

    attachments: [],
  },
  {
    id: crypto.randomUUID(),
    project_name: "E-Commerce Website",
    project_image: "https://picsum.photos/80?3",
    description: "Complete online shopping platform.",
    status: "Completed",
    priority: "High",
    start_date: "2026-05-01",
    end_date: "2026-07-01",
    created_by: "John",
    created_at: "2026-05-01",

    attachments: [],
  },
  {
    id: crypto.randomUUID(),
    project_name: "HR Portal",
    project_image: "https://picsum.photos/80?4",
    description: "Employee management portal.",
    status: "Active",
    priority: "Low",
    start_date: "2026-08-10",
    end_date: "2026-11-10",
    created_by: "Emma",
    created_at: "2026-08-10",

    attachments: [],
  },
  {
    id: crypto.randomUUID(),
    project_name: "TaskFlow",
    project_image: "https://picsum.photos/200?random=11",
    description: "Task management platform for agile teams.",
    status: "Active",
    priority: "High",
    start_date: "2025-06-01",
    end_date: "2025-09-15",
    created_by: "Admin",
    created_at: new Date().toISOString(),
    attachments: [],
  },
  {
    id: crypto.randomUUID(),
    project_name: "Hospital ERP",
    project_image: "https://picsum.photos/200?random=12",
    description: "Hospital management and patient record system.",
    status: "On Hold",
    priority: "Medium",
    start_date: "2025-04-10",
    end_date: "2025-11-20",
    created_by: "Manager",
    created_at: new Date().toISOString(),
    attachments: [],
  },
  {
    id: crypto.randomUUID(),
    project_name: "Inventory System",
    project_image: "https://picsum.photos/200?random=13",
    description: "Warehouse inventory tracking application.",
    status: "Completed",
    priority: "Low",
    start_date: "2025-01-15",
    end_date: "2025-05-30",
    created_by: "Admin",
    created_at: new Date().toISOString(),
    attachments: [],
  },
  {
    id: crypto.randomUUID(),
    project_name: "HR Portal",
    project_image: "https://picsum.photos/200?random=14",
    description: "Employee and HR management portal.",
    status: "Active",
    priority: "Medium",
    start_date: "2025-07-01",
    end_date: "2025-10-25",
    created_by: "Team Lead",
    created_at: new Date().toISOString(),
    attachments: [],
  },
  {
    id: crypto.randomUUID(),
    project_name: "Learning LMS",
    project_image: "https://picsum.photos/200?random=15",
    description: "Learning Management System for online courses.",
    status: "Completed",
    priority: "High",
    start_date: "2025-02-01",
    end_date: "2025-08-15",
    created_by: "Admin",
    created_at: new Date().toISOString(),
    attachments: [],
  },
  {
    id: crypto.randomUUID(),
    project_name: "Finance Tracker",
    project_image: "https://picsum.photos/200?random=16",
    description: "Finance and expense tracking application.",
    status: "On Hold",
    priority: "High",
    start_date: "2025-05-05",
    end_date: "2025-12-01",
    created_by: "Manager",
    created_at: new Date().toISOString(),
    attachments: [],
  },
  {
    id: crypto.randomUUID(),
    project_name: "Booking Platform",
    project_image: "https://picsum.photos/200?random=17",
    description: "Online booking and reservation system.",
    status: "Active",
    priority: "Medium",
    start_date: "2025-03-20",
    end_date: "2025-09-30",
    created_by: "Admin",
    created_at: new Date().toISOString(),
    attachments: [],
  },
  {
    id: crypto.randomUUID(),
    project_name: "Payroll System",
    project_image: "https://picsum.photos/200?random=18",
    description: "Payroll processing and salary management.",
    status: "Completed",
    priority: "Low",
    start_date: "2025-01-10",
    end_date: "2025-06-10",
    created_by: "HR",
    created_at: new Date().toISOString(),
    attachments: [],
  },
  {
    id: crypto.randomUUID(),
    project_name: "Support Center",
    project_image: "https://picsum.photos/200?random=19",
    description: "Customer support ticketing platform.",
    status: "Active",
    priority: "High",
    start_date: "2025-06-15",
    end_date: "2025-11-30",
    created_by: "Support",
    created_at: new Date().toISOString(),
    attachments: [],
  },
  {
    id: crypto.randomUUID(),
    project_name: "Real Estate CRM",
    project_image: "https://picsum.photos/200?random=20",
    description: "CRM for property dealers and clients.",
    status: "On Hold",
    priority: "Medium",
    start_date: "2025-04-01",
    end_date: "2025-10-15",
    created_by: "Admin",
    created_at: new Date().toISOString(),
    attachments: [],
  },
];
