export type SprintStatus = "Planning" | "Active" | "Completed";

export interface Sprint {
  id: string;
  sprint_name: string;
  project: string;
  goal: string;
  start_date: string;
  end_date: string;
  status: SprintStatus;
  created_by: string;
  created_at: string;
}

export const sprintData: Sprint[] = [
  {
    id: crypto.randomUUID(),
    sprint_name: "Sprint 01",
    project: "Project Management SaaS",
    goal: "Set up project management core features.",
    start_date: "2025-01-01",
    end_date: "2025-01-14",
    status: "Completed",
    created_by: "Syed Huzaifa",
    created_at: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    sprint_name: "Sprint 02",
    project: "Project Management SaaS",
    goal: "Implement authentication and authorization.",
    start_date: "2025-01-15",
    end_date: "2025-01-28",
    status: "Completed",
    created_by: "Zain Qaimi",
    created_at: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    sprint_name: "Sprint 03",
    project: "Project Management SaaS",
    goal: "Build dashboard and project overview.",
    start_date: "2025-02-01",
    end_date: "2025-02-14",
    status: "Completed",
    created_by: "Ali Raza",
    created_at: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    sprint_name: "Sprint 04",
    project: "Project Management SaaS",
    goal: "Develop project management functionality.",
    start_date: "2025-02-15",
    end_date: "2025-02-28",
    status: "Completed",
    created_by: "Ahmed Khan",
    created_at: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    sprint_name: "Sprint 05",
    project: "Project Management SaaS",
    goal: "Implement users management and permissions.",
    start_date: "2025-03-01",
    end_date: "2025-03-14",
    status: "Active",
    created_by: "Fatima Noor",
    created_at: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    sprint_name: "Sprint 06",
    project: "Project Management SaaS",
    goal: "Build task management module.",
    start_date: "2025-03-15",
    end_date: "2025-03-28",
    status: "Active",
    created_by: "Bilal Hassan",
    created_at: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    sprint_name: "Sprint 07",
    project: "Mobile App",
    goal: "Create mobile application foundation.",
    start_date: "2025-04-01",
    end_date: "2025-04-14",
    status: "Active",
    created_by: "Ayesha Malik",
    created_at: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    sprint_name: "Sprint 08",
    project: "Mobile App",
    goal: "Implement mobile authentication screens.",
    start_date: "2025-04-15",
    end_date: "2025-04-28",
    status: "Planning",
    created_by: "Usman Shah",
    created_at: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    sprint_name: "Sprint 09",
    project: "Mobile App",
    goal: "Develop profile and account management.",
    start_date: "2025-05-01",
    end_date: "2025-05-14",
    status: "Planning",
    created_by: "Sara Khan",
    created_at: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    sprint_name: "Sprint 10",
    project: "Mobile App",
    goal: "Implement notifications and alerts.",
    start_date: "2025-05-15",
    end_date: "2025-05-28",
    status: "Planning",
    created_by: "Hina Tariq",
    created_at: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    sprint_name: "Sprint 11",
    project: "E-Commerce Platform",
    goal: "Build product catalog functionality.",
    start_date: "2025-06-01",
    end_date: "2025-06-14",
    status: "Completed",
    created_by: "Muhammad Usman",
    created_at: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    sprint_name: "Sprint 12",
    project: "E-Commerce Platform",
    goal: "Implement shopping cart and checkout.",
    start_date: "2025-06-15",
    end_date: "2025-06-28",
    status: "Completed",
    created_by: "Hassan Ali",
    created_at: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    sprint_name: "Sprint 13",
    project: "E-Commerce Platform",
    goal: "Develop order management system.",
    start_date: "2025-07-01",
    end_date: "2025-07-14",
    status: "Active",
    created_by: "Maham Tariq",
    created_at: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    sprint_name: "Sprint 14",
    project: "E-Commerce Platform",
    goal: "Integrate payment processing.",
    start_date: "2025-07-15",
    end_date: "2025-07-28",
    status: "Active",
    created_by: "Hamza Ahmed",
    created_at: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    sprint_name: "Sprint 15",
    project: "CRM System",
    goal: "Create customer management module.",
    start_date: "2025-08-01",
    end_date: "2025-08-14",
    status: "Planning",
    created_by: "Sana Malik",
    created_at: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    sprint_name: "Sprint 16",
    project: "CRM System",
    goal: "Implement leads and sales pipeline.",
    start_date: "2025-08-15",
    end_date: "2025-08-28",
    status: "Planning",
    created_by: "Owais Khan",
    created_at: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    sprint_name: "Sprint 17",
    project: "CRM System",
    goal: "Build customer communication features.",
    start_date: "2025-09-01",
    end_date: "2025-09-14",
    status: "Active",
    created_by: "Maryam Noor",
    created_at: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    sprint_name: "Sprint 18",
    project: "Analytics Dashboard",
    goal: "Develop analytics and reporting features.",
    start_date: "2025-09-15",
    end_date: "2025-09-28",
    status: "Active",
    created_by: "Danish Ahmed",
    created_at: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    sprint_name: "Sprint 19",
    project: "Analytics Dashboard",
    goal: "Add charts and performance metrics.",
    start_date: "2025-10-01",
    end_date: "2025-10-14",
    status: "Planning",
    created_by: "Laiba Khan",
    created_at: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    sprint_name: "Sprint 20",
    project: "Analytics Dashboard",
    goal: "Finalize dashboard and reporting module.",
    start_date: "2025-10-15",
    end_date: "2025-10-28",
    status: "Planning",
    created_by: "Ahmed Raza",
    created_at: new Date().toISOString(),
  },
];
