export type TaskStatus = "Todo" | "In Progress" | "Review" | "Completed";

export type TaskPriority = "Low" | "Medium" | "High";

export interface Task {
  id: string;
  task_name: string;
  description: string;
  project: string;
  assignee: string;
  priority: TaskPriority;
  status: TaskStatus;
  start_date: string;
  due_date: string;
  created_by: string;
  created_at: string;
}

export const taskData: Task[] = [
  {
    id: crypto.randomUUID(),
    task_name: "Design Login UI",
    description: "Create responsive login page.",
    project: "Project Management SaaS",
    assignee: "Zain Qaimi",
    priority: "High",
    status: "In Progress",
    start_date: "2025-01-01",
    due_date: "2025-01-05",
    created_by: "Admin",
    created_at: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    task_name: "Dashboard Layout",
    description: "Build dashboard layout.",
    project: "Project Management SaaS",
    assignee: "Ali Raza",
    priority: "Medium",
    status: "Todo",
    start_date: "2025-01-03",
    due_date: "2025-01-08",
    created_by: "Admin",
    created_at: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    task_name: "Projects CRUD",
    description: "Implement CRUD operations.",
    project: "Project Management SaaS",
    assignee: "Ahmed Khan",
    priority: "High",
    status: "Review",
    start_date: "2025-01-05",
    due_date: "2025-01-12",
    created_by: "Admin",
    created_at: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    task_name: "Users Module",
    description: "Develop user management.",
    project: "CRM System",
    assignee: "Fatima Noor",
    priority: "Medium",
    status: "Completed",
    start_date: "2025-01-06",
    due_date: "2025-01-15",
    created_by: "Admin",
    created_at: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    task_name: "Task Module",
    description: "Implement task management.",
    project: "CRM System",
    assignee: "Bilal Hassan",
    priority: "High",
    status: "Todo",
    start_date: "2025-01-07",
    due_date: "2025-01-18",
    created_by: "Admin",
    created_at: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    task_name: "Notification UI",
    description: "Create notifications panel.",
    project: "HR Portal",
    assignee: "Sara Khan",
    priority: "Low",
    status: "In Progress",
    start_date: "2025-01-08",
    due_date: "2025-01-16",
    created_by: "Admin",
    created_at: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    task_name: "Reports Page",
    description: "Generate reports page.",
    project: "HR Portal",
    assignee: "Usman Shah",
    priority: "Medium",
    status: "Review",
    start_date: "2025-01-09",
    due_date: "2025-01-19",
    created_by: "Admin",
    created_at: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    task_name: "Team Module",
    description: "Create team management.",
    project: "ERP System",
    assignee: "Ayesha Malik",
    priority: "High",
    status: "Completed",
    start_date: "2025-01-10",
    due_date: "2025-01-20",
    created_by: "Admin",
    created_at: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    task_name: "Profile Settings",
    description: "Update profile page.",
    project: "ERP System",
    assignee: "Hina Tariq",
    priority: "Low",
    status: "Todo",
    start_date: "2025-01-11",
    due_date: "2025-01-22",
    created_by: "Admin",
    created_at: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    task_name: "Dark Mode",
    description: "Implement dark theme.",
    project: "Inventory System",
    assignee: "Syed Huzaifa",
    priority: "Medium",
    status: "In Progress",
    start_date: "2025-01-12",
    due_date: "2025-01-23",
    created_by: "Admin",
    created_at: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    task_name: "API Integration",
    description: "Connect frontend with backend APIs.",
    project: "Inventory System",
    assignee: "Ali Raza",
    priority: "High",
    status: "Todo",
    start_date: "2025-01-13",
    due_date: "2025-01-25",
    created_by: "Admin",
    created_at: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    task_name: "Role Permissions",
    description: "Implement role-based access.",
    project: "CRM System",
    assignee: "Ahmed Khan",
    priority: "High",
    status: "Review",
    start_date: "2025-01-14",
    due_date: "2025-01-26",
    created_by: "Admin",
    created_at: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    task_name: "Client Meeting",
    description: "Prepare sprint demo.",
    project: "ERP System",
    assignee: "Fatima Noor",
    priority: "Medium",
    status: "Completed",
    start_date: "2025-01-15",
    due_date: "2025-01-27",
    created_by: "Admin",
    created_at: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    task_name: "Authentication",
    description: "Build login & register flow.",
    project: "Project Management SaaS",
    assignee: "Syed Huzaifa",
    priority: "High",
    status: "In Progress",
    start_date: "2025-01-16",
    due_date: "2025-01-28",
    created_by: "Admin",
    created_at: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    task_name: "Bug Fixes",
    description: "Resolve reported UI bugs.",
    project: "Inventory System",
    assignee: "Usman Shah",
    priority: "Low",
    status: "Todo",
    start_date: "2025-01-17",
    due_date: "2025-01-29",
    created_by: "Admin",
    created_at: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    task_name: "Performance Optimization",
    description: "Optimize page rendering.",
    project: "CRM System",
    assignee: "Bilal Hassan",
    priority: "Medium",
    status: "Review",
    start_date: "2025-01-18",
    due_date: "2025-01-30",
    created_by: "Admin",
    created_at: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    task_name: "Email Notifications",
    description: "Implement email service.",
    project: "HR Portal",
    assignee: "Sara Khan",
    priority: "Medium",
    status: "Completed",
    start_date: "2025-01-19",
    due_date: "2025-01-31",
    created_by: "Admin",
    created_at: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    task_name: "Export Reports",
    description: "Add PDF & Excel export.",
    project: "ERP System",
    assignee: "Hina Tariq",
    priority: "Low",
    status: "Todo",
    start_date: "2025-01-20",
    due_date: "2025-02-02",
    created_by: "Admin",
    created_at: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    task_name: "User Profile",
    description: "Improve profile UI.",
    project: "Project Management SaaS",
    assignee: "Zain Qaimi",
    priority: "Medium",
    status: "In Progress",
    start_date: "2025-01-21",
    due_date: "2025-02-03",
    created_by: "Admin",
    created_at: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    task_name: "Final Testing",
    description: "Perform complete QA testing.",
    project: "Inventory System",
    assignee: "Ayesha Malik",
    priority: "High",
    status: "Completed",
    start_date: "2025-01-22",
    due_date: "2025-02-05",
    created_by: "Admin",
    created_at: new Date().toISOString(),
  },
];
