"""add project metadata columns

Revision ID: 5791026a8812
Revises: a2c0030bbda0
Create Date: 2026-08-19 16:58:16.052824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5791026a8812'
down_revision: Union[str, Sequence[str], None] = 'a2c0030bbda0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('project_image', sa.String(), nullable=True))
    op.add_column('project', sa.Column('status', sa.String(), nullable=True))
    op.add_column('project', sa.Column('priority', sa.String(), nullable=True))
    op.add_column('project', sa.Column('start_date', sa.String(), nullable=True))
    op.add_column('project', sa.Column('end_date', sa.String(), nullable=True))
    op.add_column('project', sa.Column('created_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'created_by')
    op.drop_column('project', 'end_date')
    op.drop_column('project', 'start_date')
    op.drop_column('project', 'priority')
    op.drop_column('project', 'status')
    op.drop_column('project', 'project_image')
    # ### end Alembic commands ###
