"""create kanban boards, columns and tasks tables

Revision ID: a2c0030bbda0
Revises: 
Create Date: 2026-08-19 16:35:48.851552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2c0030bbda0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kanban_boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('sprint_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kanban_boards_id'), 'kanban_boards', ['id'], unique=False)
    op.create_index(op.f('ix_kanban_boards_project_id'), 'kanban_boards', ['project_id'], unique=False)
    op.create_index(op.f('ix_kanban_boards_sprint_id'), 'kanban_boards', ['sprint_id'], unique=False)
    op.create_table('kanban_columns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('todo', 'in_progress', 'in_review', 'done', 'blocked', name='kanbanstatus'), nullable=False),
    sa.Column('wip_limit', sa.Integer(), nullable=True),
    sa.Column('order', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['kanban_boards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kanban_columns_board_id'), 'kanban_columns', ['board_id'], unique=False)
    op.create_index('ix_kanban_columns_board_order', 'kanban_columns', ['board_id', 'order'], unique=False)
    op.create_index(op.f('ix_kanban_columns_id'), 'kanban_columns', ['id'], unique=False)
    op.create_table('kanban_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('column_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('critical', 'high', 'medium', 'low', name='taskpriority'), nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('story_points', sa.Float(), nullable=True),
    sa.Column('time_estimate', sa.Float(), nullable=True),
    sa.Column('time_spent', sa.Float(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('order', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('status', sa.Enum('todo', 'in_progress', 'in_review', 'done', 'blocked', name='kanbanstatus'), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['board_id'], ['kanban_boards.id'], ),
    sa.ForeignKeyConstraint(['column_id'], ['kanban_columns.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kanban_tasks_assignee_id'), 'kanban_tasks', ['assignee_id'], unique=False)
    op.create_index('ix_kanban_tasks_board_column_order', 'kanban_tasks', ['board_id', 'column_id', 'order'], unique=False)
    op.create_index(op.f('ix_kanban_tasks_board_id'), 'kanban_tasks', ['board_id'], unique=False)
    op.create_index(op.f('ix_kanban_tasks_column_id'), 'kanban_tasks', ['column_id'], unique=False)
    op.create_index(op.f('ix_kanban_tasks_id'), 'kanban_tasks', ['id'], unique=False)
    op.create_index('ix_kanban_tasks_status', 'kanban_tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_kanban_tasks_status', table_name='kanban_tasks')
    op.drop_index(op.f('ix_kanban_tasks_id'), table_name='kanban_tasks')
    op.drop_index(op.f('ix_kanban_tasks_column_id'), table_name='kanban_tasks')
    op.drop_index(op.f('ix_kanban_tasks_board_id'), table_name='kanban_tasks')
    op.drop_index('ix_kanban_tasks_board_column_order', table_name='kanban_tasks')
    op.drop_index(op.f('ix_kanban_tasks_assignee_id'), table_name='kanban_tasks')
    op.drop_table('kanban_tasks')
    op.drop_index(op.f('ix_kanban_columns_id'), table_name='kanban_columns')
    op.drop_index('ix_kanban_columns_board_order', table_name='kanban_columns')
    op.drop_index(op.f('ix_kanban_columns_board_id'), table_name='kanban_columns')
    op.drop_table('kanban_columns')
    op.drop_index(op.f('ix_kanban_boards_sprint_id'), table_name='kanban_boards')
    op.drop_index(op.f('ix_kanban_boards_project_id'), table_name='kanban_boards')
    op.drop_index(op.f('ix_kanban_boards_id'), table_name='kanban_boards')
    op.drop_table('kanban_boards')
    # ### end Alembic commands ###
